server:
  port: 6869
  prefix: api
db:
  mysql:
    host: 8.137.155.94
    port: 3306
    username: root
    password: '123456'
    database: nest
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 20
        max-wait: 1ms
        max-idle: 10
        min-idle: 0
mail:
  host: smtp.qq.com
  username: jiayouuu@foxmail.com
  password: gtuixzhdoxbvdabi
  port: 465
jwt:
  secret: cGV0c19vbmxpbmVfYnlfamlheW91PSpLj5wuXXofO56MDWpPK35cHZmj9ui0wtfw5am4w-TR96K2
file:
  upload:
    dir: /Users/jiayou/develop/graduation_project/uploads
    allowed-extensions:
      - .jpg
      - .jpeg
      - .png
      - .pdf
      - .mp4
      - .txt
